In [1]:
import tensorflow as tf

print(tf.__version__)

2.21.0

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

X = np.random.rand(100,4)
y = np.random.randint(2,size=100)

model = Sequential()

model.add(Dense(10,activation='relu',input_shape=(4,)))
model.add(Dense(1,activation='sigmoid'))

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(X,y,epochs=5,batch_size=10)

loss,accuracy=model.evaluate(X,y)

print("Accuracy =",accuracy)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/5

C:\Users\student\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4400 - loss: 0.7255
Epoch 2/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4400 - loss: 0.7233
Epoch 3/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4600 - loss: 0.7220
Epoch 4/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4700 - loss: 0.7208
Epoch 5/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4600 - loss: 0.7193
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4600 - loss: 0.7186
Accuracy = 0.46000000834465027

In [3]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [20, 21, 19, 22],
    'Marks': [85, 90, 88, 95]
}

df = pd.DataFrame(data)

print(df)

      Name  Age  Marks
0    Alice   20     85
1      Bob   21     90
2  Charlie   19     88
3    David   22     95

In [4]:
df.loc[1]

Name     Bob
Age       21
Marks     90
Name: 1, dtype: object

In [5]:
df.loc[2]

Name     Charlie
Age           19
Marks         88
Name: 2, dtype: object

In [6]:
df.loc[1:3]

      Name  Age  Marks
1      Bob   21     90
2  Charlie   19     88
3    David   22     95

In [7]:
df.loc[0:2, ['Name', 'Marks']]

      Name  Marks
0    Alice     85
1      Bob     90
2  Charlie     88